#include "MAX_PAGE_0A0h_0AFh.h"

void MAX17320_RELAX_CONFIGURATION_REGISTER_R(void)
{
	MAX17320_READ_DATA_FROM_REGISTER(RELAX_CONFIGURATION_REGISTER_ADDRESS,&MAX17320.relax_config);
}

void MAX17320_RELAX_CONFIGURATION_REGISTER_W(uint16_t relax_config)      
{
	MAX17320_WRITE_DATA_TO_REGISTERS(RELAX_CONFIGURATION_REGISTER_ADDRESS,relax_config);
}

void MAX17320_LEARNING_CONFIGURATION_REGISTER_R(void)
{
	MAX17320_READ_DATA_FROM_REGISTER(RELAX_CONFIGURATION_REGISTER_ADDRESS,&MAX17320.learn_config);
}

void MAX17320_LEARNING_CONFIGURATION_REGISTER_W(uint16_t learn_config)    // if the value is 000h the fuel gauage, 111h the 
{
	MAX17320_WRITE_DATA_TO_REGISTERS(RELAX_CONFIGURATION_REGISTER_ADDRESS,learn_config);
}

void MAX17320_CURRENT_LIMIT_ALERT_THRESHOLD_REGISTER_R(void)
{
	MAX17320_READ_DATA_FROM_REGISTER(CURRENT_ALERT_THRESHOLD_REGISTER_ADDRESS,&MAX17320.ialrtth);
}

void MAX17320_CURRENT_LIMIT_ALERT_THRESHOLD_REGISTER_W(uint16_t ialrtth)
{
	MAX17320_WRITE_DATA_TO_REGISTERS(CURRENT_ALERT_THRESHOLD_REGISTER_ADDRESS,ialrtth);	
}

void MAX17320_PROTECTION_ALERT_REGISTER(void)
{
	MAX17320_READ_DATA_FROM_REGISTER(PROTECTION_ALERT_REGISTER_ADDRESS,&MAX17320.protection_alert_register);
}
