#ifndef __MAX_PAGE_0D0h_0DFh_H
#define __MAX_PAGE_0D0h_0DFh_H

#include "main.h"
#include "i2c.h"
#include "MAX17320.h"

								//START OF PAGE 0D0h TO 0DFh //
#define SOC_HOLD_REGISTER_ADDRESS																0XD0
#define AVERAGE_CELL_4_REGISTER_ADDRESS													0XD1
#define AVERAGE_CELL_3_REGISTER_ADDRESS													0XD2
#define AVERAGE_CELL_2_REGISTER_ADDRESS													0XD3
#define AVERAGE_CELL_1_REGISTER_ADDRESS													0XD4
#define CELL_4_REGISTER_ADDRESS																	0XD5
#define CELL_3_REGISTER_ADDRESS																	0XD6
#define CELL_2_REGISTER_ADDRESS																	0XD7
#define CELL_1_REGISTER_ADDRESS																	0XD8
#define PROTECTION_STATUS_REGISTER_ADDRESS											0XD9
#define BATTERY_REGISTER_ADDRESS																0XDA
#define PCKP_REGISTER_ADDRESS																		0XDB
#define AT_QRESIDUAL_REGISTER_ADDRESS														0XDC
#define AT_TIME_TO_EMPTY_REGISTER																0XDD
#define AT_AVERAGE_SOC_REGISTER_ADDRESS													0XDE   //not implemented
#define AT_AVERAGE_CAPACITY_REGISTER_ADDRESS										0XDF

void MAX17320_SOC_HOLD_REGISTER_R(void);
void MAX17320_AVERAGE_CELL_4_REGISTER_R(void);
void MAX17320_AVERAGE_CELL_3_REGISTER_R(void);
void MAX17320_AVERAGE_CELL_2_REGISTER_R(void);
void MAX17320_AVERAGE_CELL_1_REGISTER_R(void);
void MAX17320_CELL_4_REGISTER_R(void);
void MAX17320_CELL_3_REGISTER_R(void);
void MAX17320_CELL_2_REGISTER_R(void);
void MAX17320_CELL_1_REGISTER_R(void);
void MAX17320_PROTECTION_STATUS_REGISTER_R(void);
void MAX17320_BATTERY_REGISTER_R(void);
void MAX17320_PACK_REGISTER_R(void);
void MAX17320_AT_QRESIDUAL_REGISTER_R(void);
void MAX17320_AT_TIME_TO_EMPTY_REGISTER_R(void);

void MAX17320_AT_AVERAGE_CAPACITY_REGISTER_R(void);

#endif
